---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Batch Job definition for Nextflow'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "AWS Batch Job Definition Config"
        Parameters:
        - NFJobQueue
        - ImageId
        - ECSRoleArn
        - AWSRegion
        - BaseName
    ParameterLabels:
      NFJobQueue:
        default: AWS Batch Job Queue name to execute Nextflow jobs
      ImageId:
        default: ECR Repo name to run the Nextflow run command
      ECSRoleArn:
        default: ECS Task Execution Role Arn
      AWSRegion:
        default: AWS Region the job is running in
      BaseName:
        default: Base Name

Parameters:
  NFJobQueue:
    Type: String
    Description: 'The name of the AWS Batch Job Queue to execute Nextflow jobs'
  ImageId:
    Type: String
    Description: 'The name of the ECR repo'
  ECSRoleArn:
    Type: String
    Description: 'Arn of the ECS Task Execution Role'
  AWSRegion:
    Type: String
    Description: 'AWS Region the job is running in'
  BaseName:
    Type: String
    Description: Name used for the different components
    Default: nextflow

Resources:
  JobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      JobDefinitionName: !Sub ${BaseName}-job-definition
      ContainerProperties:
        Image: !Ref ImageId
        ResourceRequirements:
        - Type: VCPU
          Value: '16'
        - Type: MEMORY
          Value: '1024'
        ExecutionRoleArn: !Ref ECSRoleArn
        Command:
        - /usr/local/bin/entrypoint.sh
        Environment:
        - Name: PIPELINE_URL
          Value: https://github.com/seqeralabs/nextflow-tutorial
        - Name: NF_SCRIPT
          Value: main.nf
        - Name: NF_JOB_QUEUE
          Value: !Ref NFJobQueue
        - Name: AWS_REGION
          Value: !Ref AWSRegion
      Timeout:
        AttemptDurationSeconds: 500
      RetryStrategy:
        Attempts: 1
